MW-7 Landing page
Design-ITUS-HCMUS/main-website pull request #1
Opened 2024-02-22 09:22 UTC by MinEn1712

- Add landing page
- Add `react-swipeable-views` and `react-swipeable-views-utils` for Carousel component
- Add `framer-motion` for `useScroll` hook
- Add `InfiniteLooper` from old website source code
- Create `title` typography variant in light.ts

2024-02-23 14:13 UTC, NganTrucLe reviewed
Chắc có gì bổ sung cho t thim mí cái stories lun nhe, cái component nào cũng phải có stories hết é

2024-02-23 14:13 UTC, NganTrucLe commented on src/libs/ui/components/Footer.tsx
> +      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
Hạn chế inline style giúp teo nhe, có thể thử Stack nè, hoặc là chuyển sang styled component tại thấy ở dưới cũng dùng lại

2024-02-23 14:13 UTC, NganTrucLe commented on src/libs/ui/components/Footer.tsx
> +                  <Typography variant='body2'>Liên hệ</Typography>
Hình như default đã là body2 rùi nha nên để variant hơi thừa. cái đường link fb với lại mail á, thêm target='_blank' để nó mở tab ms

2024-02-23 16:36 UTC, vmathu requested changes

2024-02-23 16:36 UTC, vmathu commented on src/app/_components/LeaderCard.tsx
> +            style={{ width: '100%', objectFit: 'cover' }}
hmmmm dù để fix size nhma style width 100% vẫn làm nó sai tỉ lệ k giống des nè vì màn t là 1920px á, nếu được chắc để tỉ lệ kiểu 4:3 hay s đó chứ đừng để fix size nhe, kiểu `aspectRatio: "16 / 9"`
![image](https://github.com/Design-ITUS-HCMUS/main-website/assets/91612623/07fb3011-1fbc-48a8-88e8-501af90a62ff)

2024-02-23 16:36 UTC, vmathu commented on src/libs/ui/components/Footer.tsx
mình sẽ k dùng `<a />` cho link nha, với typo mình có thể, chắc coi thêm bên repo admin cách mn làm ha
`
<Typography component={Link} href={linkHref} variant='linkPrimary'>
        {linkText}
</Typography>
`

2024-02-23 16:36 UTC, vmathu commented on src/app/_components/Partners.tsx
> +import InfiniteLooper from '../../libs/ui/components/InfiniteLooper';
bên file `tsconfig.json` sửa `"@components": ["./src/libs/ui/components"]` thành `"@components/*": ["./src/libs/ui/components/*"]` để ở đây có thể import kiểu `import InfiniteLooper from '@components/InfiniteLooper';` nha

2024-02-23 16:36 UTC, vmathu commented on src/libs/ui/components/InfiniteLooper.tsx
> +  animation: `${slideAnim} linear infinite`,
với code cũ có nghĩa là những `.looper__listInstance` child cụa `.looper__innerList[data-animate='true']` mới có animation này á, còn `data-animate='false'` thì `animation: none` nên là handle lại khúc này nha, như hiện tại là nó k quan tâm `data-animation` á nên true false j cx apply animation dzo
![image](https://github.com/Design-ITUS-HCMUS/main-website/assets/91612623/f089656e-f60a-4442-b172-73de621b89ef)

2024-03-04 15:26 UTC, NganTrucLe requested changes
Tổng quát đã ổn, vẫn bị glitch ở ntt nhưng m có thể raise 1 task bug ở Jira nha, rồi 1 hồi quay lại đứa khác làm cho, h mình qua task mới

2024-03-04 15:26 UTC, NganTrucLe commented on src/libs/data/eventData.json
> +    "image": "/images/eventimage.png",
![image](https://github.com/Design-ITUS-HCMUS/main-website/assets/97326103/70a0d593-e00f-450d-b1cf-20e049320b80)

2024-03-04 15:26 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +        navbarRef.current.style.borderBottom = '2px solid rgb(0, 0, 0)';
`2px solid ${colors.blue[500]}`

2024-03-12 13:51 UTC, NganTrucLe approved these changes

2024-03-12 13:55 UTC, merged